### ISSUE TITLE
camera intrinsics of Simsin dataset

### ISSUE THREAD

**Issue by rainfall1998** [facebookresearch/DistDepth#1]
It is appreciated to publish new datasets for indoor environment, and thanks for your working. I have some questions of the Simsin dataset.

1. Where can I find the camera intrinsics of Simsin dataset? The dataset zip does include the readme or camera intrinsics for the dataset. 
2. Whether a dataset.py file that reads the simsin dataset can be published ?

Thanks for your working and looking forward to your reply

**Comment by choyingw** [comment]
I'll work on updates in next few days and will provide more details on the SimSIN generation.

**Comment by rainfall1998** [comment]
Thanks for your reply and working! Recently I want to train a network on SinSIN for some tests. Would you mind giving the  camera intrinsics of SimSIN dataset first? Your work would be extremely helpful.

**Comment by choyingw** [comment]
The intrinsic is [[0.5, 0, 0.5, 0], [0, 0.5, 0.5, 0], [0, 0, 1, 0], [0, 0, 0, 1]], normalized by side length = 512 pix.

That is, fx = fy = 256 pix, and (cx, cy) = (256,256)

**Comment by rainfall1998** [comment]
Thanks for your prompt response!
