### ISSUE TITLE
Question about preparing NYUv2 dataset for evaluation

### ISSUE THREAD

**Issue by afazel** [facebookresearch/DistDepth#11]
Hi,
Thank you so much for releasing your code.
I am trying to run the evaluation script for NYUv2 dataset. Based on the README the format of the data should be like this:
 ```
 ├── NYUv2
        ├── img_val
           ├── 00001.png
           ......
        ├── depth_val
           ├── 00001.npy
           ......
           ......
        ├── NYUv2.txt
```
I have downloaded NYUv2 labeled dataset from [here](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html) which is a `.m` file. Is this the dataset you used for evaluation? if yes do you have any scripts on how to extract data from this `.m` file compatible with the format mentioned in the README?

**Comment by choyingw** [comment]
#7

**Comment by afazel** [comment]
Thank you
