### ISSUE TITLE
google drive data download fail

### ISSUE THREAD

**Issue by aiforworlds** [facebookresearch/DistDepth#14]
File download fails because a single file of Google drive data is too large, example UniSIN: , 457G(https://drive.google.com/file/d/15Pz2pr9u1nS809wXYGroEDFEprBVCTF0/view?usp=sharing)

**Comment by choyingw** [comment]
Google drive has a download quota limit. You can "make a copy" of your file and download it to avoid the quota limit (see the updated project page instruction). You can also download the split chunks of data.

**Comment by aiforworlds** [comment]
Thank you for your replies!   I've read the instructions, But the file is too large and I don't have enough space on my cloud disk to copy it, Why not upload it to the Baidu cloud disk, Baidu cloud disk should be better to use.

**Comment by choyingw** [comment]
Please use the split zip file instead. It's 50G each file and the quota limit is per-day basis. If you meet the limit, then please retry later. Thank you.

**Comment by aiforworlds** [comment]
thanks
