### ISSUE TITLE
About UniSIN data collect method

### ISSUE THREAD

**Issue by aiforworlds** [facebookresearch/DistDepth#17]
When you use zed2i camera to collect data, Just hold it in your hands or use others stabilizing device?  I found out when I tried, the video will shake when you hold it directly, Is there any way you can stabilize the zed2i camera while you're collecting data, thank you very much

**Comment by choyingw** [comment]
We use a hand-held tripod to stabilize (as shown in paper figure)

**Comment by aiforworlds** [comment]
thank you
