### ISSUE TITLE
how convert to point cloud? and how to train?

### ISSUE THREAD

**Issue by lucasjinreal** [facebookresearch/DistDepth#2]
how convert to point cloud? and how to train?

**Comment by choyingw** [comment]
I'll try to make updates in a few days.

**Comment by lucasjinreal** [comment]
thank u! hoping for your result!

**Comment by lucasjinreal** [comment]
btw, does convert to point cloud must have camera instrincis, what about some internet images?

**Comment by choyingw** [comment]
Yes, you need a camera intrinsic to convert depth to 3D points.

Ph.D. candidate of Computer Science Department
University of Southern California

**Comment by choyingw** [comment]
I updated the README.md to add pointcloud visualization (associated camera parameters are also specified in the file) Please check.

**Comment by choyingw** [comment]
The training codes are released. Thanks!

**Comment by zhengqianisme** [comment]
How to get '0000_depth.npy' ?
