### ISSUE TITLE
Normalization input image for DPT

### ISSUE THREAD

**Issue by nuko7055** [facebookresearch/DistDepth#28]
I found that the normalization of the DPT input is done twice in the program. Is this correct ?

https://github.com/facebookresearch/DistDepth/blob/36f9108592b76892e1d987a4bf176e7584c8323c/execute_func.py?plain=1#L251-L254

https://github.com/facebookresearch/DistDepth/blob/36f9108592b76892e1d987a4bf176e7584c8323c/dpt_networks/dpt_depth.py?plain=1#L77-L79

**Comment by choyingw** [comment]
Thanks for cathing this. I'll make a revision.

**Comment by choyingw** [comment]
fixed
